version: 1
services:
  - type: web
    name: discord-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_TOKEN
        value: your_discord_bot_token_here  # Ganti dengan token bot yang sesuai
    autoDeploy: true
    plan: free
    routes:
      - type: static
        path: /
        file: index.html
